---
abstract: 'Remove multiple slashes in your paths automatically'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  Module::Build: 0.3601
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-NoMultipleSlashes
requires:
  Plack::Middleware: 0
  parent: 0
resources:
  repository: http://github.com/xsawyerx/plack-middleware-nomultipleslashes
version: 0.001
